version: '3.7'

networks:
  redis_ml_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.82.0.0/24

services:
  haredis:
    build:
      context: .
      dockerfile: include/backend.Dockerfile
    container_name: ${SERVICE_NAME}
    image: "${SERVICE_IMAGE}:${SERVICE_TAG}"
    hostname: ${SERVICE_NAME}
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PORT=${API_PORT}
    restart: unless-stopped
    volumes:
      - ./:${API_VOL}/
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      redis_ml_network:
        ipv4_address: ${IP_API}
    command: python3 api.py
    #command: /bin/bash


  # ==================== #

  redis:
    image: redis:${REDIS_TAG}
    build:
      context: .
      dockerfile: include/redis.Dockerfile
      args:
        REDIS_TAG: ${REDIS_TAG}
    command: redis-server --include /usr/local/etc/redis/redis.conf
    container_name: ${REDIS_HOST}
    restart: always
    volumes:
      - ./include/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      redis_ml_network:
        ipv4_address: ${IP_REDIS}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s