version: '3.7'

networks:
  redis_ml_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.82.0.0/24

services:
  # ==================== #

  redis:
    image: redis:${REDIS_TAG}
    build:
      context: .
      dockerfile: include/redis.Dockerfile
      args:
        REDIS_TAG: ${REDIS_TAG}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    container_name: ${REDIS_HOST}
    restart: always
    volumes:
      - ./include/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      redis_ml_network:
        ipv4_address: ${IP_REDIS}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s